//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangDaQuy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSSERVICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSSERVICE()
        {
            this.SERVICELISTs = new HashSet<SERVICELIST>();
        }
    
        public string ID { get; set; }
        public string IDCustomer { get; set; }
        public System.DateTime DateBooking { get; set; }
        public string Stt { get; set; }
    
        public virtual INFOCUSTOMER INFOCUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICELIST> SERVICELISTs { get; set; }
    }
}
