//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangDaQuy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORTEDITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMPORTEDITEM()
        {
            this.ITEMS = new HashSet<ITEM>();
            this.ITEMBILLFORMs = new HashSet<ITEMBILLFORM>();
        }
    
        public string ID { get; set; }
        public string NameItem { get; set; }
        public string IDProd { get; set; }
        public string IDForm { get; set; }
        public string IDMaterial { get; set; }
        public Nullable<int> Quantity { get; set; }
        public double PurchasePrice { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Total { get; set; }
        public System.DateTime DatePurchase { get; set; }
        public string Descript { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual FORMCATEGORY FORMCATEGORY { get; set; }
        public virtual MATERIALCATEGORY MATERIALCATEGORY { get; set; }
        public virtual INFOPROVIDER INFOPROVIDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM> ITEMS { get; set; }
        public virtual CART CART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEMBILLFORM> ITEMBILLFORMs { get; set; }
    }
}
