//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangDaQuy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public string ID { get; set; }
        public string IDItemForm { get; set; }
        public string IDItem { get; set; }
        public double Total { get; set; }
        public Nullable<int> Quantity { get; set; }
        public System.DateTime DateSell { get; set; }
    
        public virtual IMPORTEDITEM IMPORTEDITEM { get; set; }
        public virtual ITEMFORM ITEMFORM { get; set; }
    }
}
