//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangDaQuy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICELIST
    {
        public string IDCusService { get; set; }
        public string IDService { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Costs { get; set; }
        public Nullable<double> PriceDiscounted { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Prepay { get; set; }
        public Nullable<double> Remain { get; set; }
        public System.DateTime DateReturn { get; set; }
        public string Stt { get; set; }
    
        public virtual CUSSERVICE CUSSERVICE { get; set; }
        public virtual SERVICECATEGORY SERVICECATEGORY { get; set; }
    }
}
