//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangDaQuy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORTEDITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMPORTEDITEM()
        {
            this.ITEMBILLs = new HashSet<ITEMBILL>();
        }
    
        public string ID { get; set; }
        public string IDProd { get; set; }
        public string IDOrgItem { get; set; }
        public Nullable<int> Quantity { get; set; }
        public double PurchasePrice { get; set; }
        public Nullable<double> Total { get; set; }
        public System.DateTime DatePurchase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEMBILL> ITEMBILLs { get; set; }
        public virtual ORIGINALITEM ORIGINALITEM { get; set; }
        public virtual INFOPROVIDER INFOPROVIDER { get; set; }
    }
}
