//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangDaQuy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFOPROVIDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFOPROVIDER()
        {
            this.IMPORTEDITEMS = new HashSet<IMPORTEDITEM>();
            this.ITEMBILLFORMs = new HashSet<ITEMBILLFORM>();
        }
    
        public string ID { get; set; }
        public string NameProd { get; set; }
        public string Addr { get; set; }
        public string Phone { get; set; }

        public Nullable<int> stt { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPORTEDITEM> IMPORTEDITEMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEMBILLFORM> ITEMBILLFORMs { get; set; }
    }
}
