//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangDaQuy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CuaHangDaQuyEntities : DbContext
    {
        public CuaHangDaQuyEntities()
            : base("name=CuaHangDaQuyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<CART> CARTS { get; set; }
        public virtual DbSet<CUSSERVICE> CUSSERVICEs { get; set; }
        public virtual DbSet<FORMCATEGORY> FORMCATEGORies { get; set; }
        public virtual DbSet<IMPORTEDITEM> IMPORTEDITEMS { get; set; }
        public virtual DbSet<INFOCUSTOMER> INFOCUSTOMERs { get; set; }
        public virtual DbSet<INFOPROVIDER> INFOPROVIDERs { get; set; }
        public virtual DbSet<INFOSTAFF> INFOSTAFFs { get; set; }
        public virtual DbSet<ITEMBILL> ITEMBILLs { get; set; }
        public virtual DbSet<ITEMBILLFORM> ITEMBILLFORMs { get; set; }
        public virtual DbSet<ITEMFORM> ITEMFORMs { get; set; }
        public virtual DbSet<ITEM> ITEMS { get; set; }
        public virtual DbSet<MATERIALCATEGORY> MATERIALCATEGORies { get; set; }
        public virtual DbSet<ORIGINALITEM> ORIGINALITEMs { get; set; }
        public virtual DbSet<SERVICECATEGORY> SERVICECATEGORies { get; set; }
        public virtual DbSet<SERVICELIST> SERVICELISTs { get; set; }
        public virtual DbSet<UNIT> UNITs { get; set; }
    
        public virtual int USP_Carts(string idorg)
        {
            var idorgParameter = idorg != null ?
                new ObjectParameter("idorg", idorg) :
                new ObjectParameter("idorg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_Carts", idorgParameter);
        }
    
        public virtual int USP_UpdateImportedItems(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UpdateImportedItems", idParameter);
        }
    
        public virtual int USP_UpdateItems(string iditemform, string idorg)
        {
            var iditemformParameter = iditemform != null ?
                new ObjectParameter("iditemform", iditemform) :
                new ObjectParameter("iditemform", typeof(string));
    
            var idorgParameter = idorg != null ?
                new ObjectParameter("idorg", idorg) :
                new ObjectParameter("idorg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UpdateItems", iditemformParameter, idorgParameter);
        }
    
        public virtual int USP_UpdateServiceList(string idcusservice, string idservice)
        {
            var idcusserviceParameter = idcusservice != null ?
                new ObjectParameter("idcusservice", idcusservice) :
                new ObjectParameter("idcusservice", typeof(string));
    
            var idserviceParameter = idservice != null ?
                new ObjectParameter("idservice", idservice) :
                new ObjectParameter("idservice", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UpdateServiceList", idcusserviceParameter, idserviceParameter);
        }
    }
}
